name: Release

on:
  release:
    types: [published]

jobs:
  Release-Java:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2023-22.04

    name: "Release: Generate Java Everybot"
    steps:
        - uses: actions/checkout@v2

        - name: "Zip Java Everybot"
          run: zip -r Everybot_Java_Release.zip Java

        - name: "Publish Java Everybot"
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ github.server_url }}/${{ github.repository }}/releases/latest
            asset_path: ./Everybot_Java_Release.zip
            asset_name: Everybot_Java_Release.zip
            asset_content_type: application/zip

  Release-Cpp:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2023-22.04

    name: "Release: Generate Cpp Everybot"
    steps:
      - uses: actions/checkout@v2

      - name: "Zip Cpp Everybot"
        run: zip -r Everybot_Cpp_Release.zip Cpp

      - name: "Publish Cpp Everybot"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.server_url }}/${{ github.repository }}/releases/latest
          asset_path: ./Everybot_Cpp_Release.zip
          asset_name: Everybot_Cpp_Release.zip
          asset_content_type: application/zip

  Release-Python:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2023-22.04

    name: "Release: Generate Python Everybot"
    steps:
      - uses: actions/checkout@v2

      - name: "Zip Python Everybot"
        run: zip -r Everybot_Python_Release.zip Python

      - name: "Publish Python Everybot"
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.server_url }}/${{ github.repository }}/releases/latest
          asset_path: ./Everybot_Python_Release.zip
          asset_name: Everybot_Python_Release.zip
          asset_content_type: application/zip