# This is a basic workflow to build robot code.

name: robot-code-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch.
on:
  push:
    branches: ["main", "rolling-release"]
  pull_request:
    branches: ["main", "rolling-release"]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Rio-Java:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2023-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Declares the repository safe and not under dubious ownership.
      - name: Add repository to git safe directories
        working-directory: ./Java/Rio
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        working-directory: ./Java/Rio
        run: chmod +x ./gradlew

      # Runs a single command using the runners shell
      - name: Compile and run tests on robot code
        working-directory: ./Java/Rio
        run: ./gradlew build --stacktrace

  Rio-Cpp:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2023-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Declares the repository safe and not under dubious ownership.
      - name: Add repository to git safe directories
        working-directory: ./Cpp/Rio
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      # Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        working-directory: ./Cpp/Rio
        run: chmod +x ./gradlew

      # Runs a single command using the runners shell
      - name: Compile and run tests on robot code
        working-directory: ./Cpp/Rio
        run: ./gradlew build --stacktrace